name: Nawe Ngwino Integration Test

on: [push]

jobs:
     build:
     runs-on: ubuntu-latest
     strategy:
     matrix:
     node-version: [13.14.x]

     steps:
     -name: Check the repository code
     uses: actions/checkout@v2
     -name: Use Node.js certain version
     uses: actions/setup-node@v1
     with:
     node-version: ${{matrix.node-version}}

     -name: Install dependencies
     run: |
     yarn ci
     yarn test
